const express = require("express");
const router = express.Router();
const mainController = require('../controllers/mainController.js');
const routes_validation = require('../middlewares/routes_validation.js');
const alumnado_validation = require('../middlewares/views_validation.js');
router.get('/',mainController.inicio);
router.get('/registro',mainController.registro);
router.post('/crear_usuario',mainController.crear_usuario);
router.post('/iniciar_session',mainController.iniciar_session);
router.get('/alumno',routes_validation,mainController.vista_alumno);
router.get('/alumnado',alumnado_validation,mainController.vista_notas);
router.post("/guardar_nota",mainController.guardar_nota);
router.get("/admin",mainController.adminView);
module.exports = router;
